import React, { useEffect, useState } from 'react';

const TermsOfUse: React.FC = () => {
  const [showTerms, setShowTerms] = useState(true);

  useEffect(() => {
    document.title = 'Terms of Use | Noble Citizen Foundation';
    window.scrollTo(0, 0); 
  }, []);

  return (
    <section className="Section bg-white text-gray-800">
      <div className="container-custom">
        <div className="min-h-screen py-16 px-4 sm:px-8 lg:px-20 text-gray-800">
          <h1 className="text-3xl font-bold text-center mb-8">Terms of Use</h1>

          <div className="mb-6 border-b border-gray-300 pb-4">
            <button
              onClick={() => setShowTerms(!showTerms)}
              className="text-left w-full font-semibold text-lg hover:text-red-500 transition"
            >
              ➤ Terms of Use
            </button>

            {showTerms && (
              <div className="mt-4 text-justify space-y-4">
                <p>
                  This document is an electronic record in terms of the Information Technology Act, 2000 and rules made thereunder, as applicable, and the amended provisions pertaining to electronic records in various statutes as amended by the Information Technology Act, 2000. This electronic record is generated by a computer system and does not require any physical or digital signatures.
                </p>
                <p>
                  This document is published in accordance with Rule 3 (1) of the Information Technology (Intermediaries Guidelines) Rules, 2011, requiring publishing the rules and regulations, privacy policy, and Terms of Use for access or usage of the domain https://noblecitizenfoundation.org (the "Website"), including the related mobile site and application (collectively, the "Platform").
                </p>
                <p>
                  The Platform is owned by Noble Citizen Foundation, with its registered office at 364 Prakash Mohalla, 1st Floor, East of Kailash, New Delhi, India (referred to as "Platform Owner", "we", "us", or "our").
                </p>
                <p>
                  Your use of the Platform and associated services/tools are governed by these Terms of Use, including applicable policies referenced herein. By merely using the Platform, you agree to be bound by these Terms, which shall constitute a binding agreement between you and the Platform Owner.
                </p>
                <p>
                  These Terms of Use apply to your use of our website, goods (if applicable), or services (collectively, “Services”). Any additional or conflicting terms proposed by you are expressly rejected and shall have no legal effect.
                </p>
                <p>
                  These Terms of Use may be modified at any time without prior notice. It is your responsibility to periodically review them for updates.
                </p>
                <p>
                  For the purpose of these Terms of Use, “you”, “your”, or “user” refers to any natural or legal person who has agreed to use the Platform or Services.
                </p>
                <p className="font-semibold text-center">
                  ACCESSING, BROWSING OR OTHERWISE USING THE PLATFORM INDICATES YOUR AGREEMENT TO THESE TERMS OF USE.
                </p>

                <p>The use of the Platform and Services is subject to the following terms:</p>

                <ul className="list-disc list-inside space-y-2">
                  <li>You must provide true, accurate, and complete information during and after registration. You are responsible for all activities conducted through your account.</li>
                  <li>We do not guarantee the accuracy, completeness, or timeliness of any information on the Platform. You acknowledge potential inaccuracies and use such content at your own risk.</li>
                  <li>You are solely responsible for assessing whether the Services meet your requirements.</li>
                  <li>The Platform’s content is our intellectual property. You have no rights over its layout, design, or content.</li>
                  <li>Unauthorized use of the Platform may result in legal action.</li>
                  <li>You agree to pay all charges associated with availing Services.</li>
                  <li>You agree not to use the Platform or Services for unlawful or prohibited activities.</li>
                  <li>The Platform may contain links to third-party sites. We are not responsible for their content or policies.</li>
                  <li>By initiating any transaction, you enter into a binding contract with the Platform Owner.</li>
                  <li>You shall indemnify and hold harmless the Platform Owner and affiliates from any claims or liabilities arising from your breach of these Terms or legal violations.</li>
                  <li>We are not liable for delays or failures due to force majeure events.</li>
                  <li>These Terms shall be governed by Indian law. Any disputes shall fall under the jurisdiction of New Delhi courts.</li>
                </ul>

                <p>
                  All concerns or communications related to these Terms must be directed to us using the contact information provided on this website.
                </p>
              </div>
            )}
          </div>
        </div>
      </div>
    </section>
  );
};

export default TermsOfUse;
